name: Generate PlantUML Diagrams

on:
  push:
    paths:
      - 'PlantUML/**.puml'
      - '.github/workflows/generate-diagrams.yml'
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install PlantUML
        run: |
          curl -L -o plantuml.jar https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar

      - name: Generate Diagrams
        run: |
          find PlantUML -name '*.puml' -exec java -jar plantuml.jar -tpng -o ./Out {} +
          ls -l Out

      - name: Commit generated diagrams
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-generate PlantUML diagrams" || echo "No changes to commit"
          git push
