name: Release and Push to GHCR

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.semantic-release.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run semantic release
        id: semantic-release
        uses: go-semantic-release/action@v1.24.1
        with:
            github-token: ${{ secrets.PAT }}
            allow-initial-development-versions: true

      - name: Output the new version
        run: echo "New version is ${{ steps.semantic-release.outputs.version }}"